# Generated by Django 1.11.25 on 2019-10-12 21:39

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatablearticletranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="example.TranslatableArticle",
            ),
        ),
    ]
